# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c178a7a6160947254735f9dd86ff851401db403e474fd75634b3b8882684ce89255f695dd4b4d9a8a2d717a9589883daa38baead0110bd094948b53b6458bf1d

test:
  secret_key_base: ea7835a9669915e700037b8bcbb142e24fa5d04f67f522b8548570bd12c590f21b583593379dd13331cc102319a858a203a724ba46ebcc32b5c5ce7abe7fde85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
